import type { Metadata } from 'next';
import './globals.css';
import { CounterStoreProvider } from '@/providers/counter-store-provider';
import Providers from '@/providers/react-query-provider';


export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<CounterStoreProvider>{children}</CounterStoreProvider>
				</Providers>
			</body>
		</html>
	);
}
